project_id = "exjeyrnttrevrbwykmuj"

[functions]
  [functions.bookmarks]
    verify_jwt = false
  [functions.summaries]
    verify_jwt = false
  [functions.rag_query]
    verify_jwt = false
  [functions.notes]
    verify_jwt = false
  [functions.process-bookmark]
    verify_jwt = false
